import sys, os
# Allow running standalone or imported as module
if __name__ == '__main__':
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from app import app, db, Property

listings = [
    # COMMERCIAL TO LET — AVAILABLE
    {'address': 'Units 1-3, Plato Place, 72-74 St Dionis Road', 'postcode': 'SW6 4TU', 'property_type': 'Office Suite', 'size': 2470, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': True,  'area': 'Fulham',          'use_class': 'office',      'listing_price': 98800,   'listing_price_unit': 'pa',   'lat': 51.4753, 'lng': -0.2012, 'photo_id': 'photo-1497366216548-37526070297c', 'blurb': 'Bright, spacious office space just off Parsons Green, offering excellent natural light in a quiet yet well-connected Fulham location.'},
    {'address': 'Lockside House, 1 Thurstan Street',             'postcode': 'SW6 2XD', 'property_type': 'Office Suite', 'size': 936,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea Creek',   'use_class': 'office',      'listing_price': 42120,   'listing_price_unit': 'pa',   'lat': 51.4734, 'lng': -0.1818, 'photo_id': 'photo-1497366412874-3415097a27e7', 'blurb': 'Fully fitted and furnished ground floor commercial unit within the prestigious Chelsea Creek development — ready to occupy immediately.'},
    {'address': 'Unit 202-203, Harbour Yard',                   'postcode': 'SW10 0XD','property_type': 'Office Suite', 'size': 1665, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': True,  'area': 'Chelsea Harbour',  'use_class': 'office',      'listing_price': 7565,    'listing_price_unit': 'pcm',  'lat': 51.4737, 'lng': -0.1837, 'photo_id': 'photo-1497366754035-f200968a6e72', 'blurb': 'Duplex office suite to let in Harbour Yard, Chelsea Harbour — modern riverside workspace in a prestigious West London location with stunning waterfront views.'},
    {'address': 'Unit 307, Harbour Yard',                       'postcode': 'SW10 0XD','property_type': 'Office Suite', 'size': 750,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea Harbour',  'use_class': 'office',      'listing_price': 3360,    'listing_price_unit': 'pcm',  'lat': 51.4738, 'lng': -0.1839, 'photo_id': 'photo-1497366811353-6870744d04b2', 'blurb': 'Duplex office space to let in Harbour Yard, Chelsea Harbour — modern riverside workspace with access to all building amenities.'},
    {'address': 'Unit 206, Harbour Yard',                       'postcode': 'SW10 0XD','property_type': 'Office Suite', 'size': 555,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea Harbour',  'use_class': 'office',      'listing_price': 2800,    'listing_price_unit': 'pcm',  'lat': 51.4736, 'lng': -0.1835, 'photo_id': 'photo-1497366216548-37526070297c', 'blurb': "Prime office space to let in Harbour Yard, Chelsea Harbour — a self-contained suite in one of West London's finest business addresses."},
    {'address': 'Unit 210/210a, Harbour Yard',                  'postcode': 'SW10 0XD','property_type': 'Office Suite', 'size': 2824, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea Harbour',  'use_class': 'office',      'listing_price': 15205,   'listing_price_unit': 'pcm',  'lat': 51.4739, 'lng': -0.1841, 'photo_id': 'photo-1497366412874-3415097a27e7', 'blurb': 'One of the largest available suites at Harbour Yard — a substantial riverside office over two floors with exceptional natural light and water views.'},
    {'address': 'Unit 208, Harbour Yard',                       'postcode': 'SW10 0XD','property_type': 'Office Suite', 'size': 538,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea Harbour',  'use_class': 'office',      'listing_price': 2695,    'listing_price_unit': 'pcm',  'lat': 51.4737, 'lng': -0.1838, 'photo_id': 'photo-1497366754035-f200968a6e72', 'blurb': 'Compact, well-appointed office suite to let in the prestigious Harbour Yard development on the Chelsea waterfront.'},
    {'address': 'Suite 7, Station Court, 2 Station Court',      'postcode': 'SW6 2PY', 'property_type': 'Office Suite', 'size': 430,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Fulham',          'use_class': 'office',      'listing_price': 750,     'listing_price_unit': 'pcm',  'lat': 51.4726, 'lng': -0.1789, 'photo_id': 'photo-1497366811353-6870744d04b2', 'blurb': 'Modern self-contained office to let next to Imperial Wharf — comfort cooling, kitchenette and excellent transport links to central London.'},
    {'address': 'Furniture & Arts Building First Floor, 533 Kings Road', 'postcode': 'SW10 0TZ', 'property_type': 'Office Suite', 'size': 3142, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': True, 'area': 'Chelsea', 'use_class': 'office', 'listing_price': 110000, 'listing_price_unit': 'pa', 'lat': 51.4891, 'lng': -0.1836, 'photo_id': 'photo-1555396273-367ea4eb4db5', 'blurb': "First floor office, showroom and leisure space on the King's Road — an exceptional opportunity in one of Chelsea's most celebrated buildings."},
    {'address': '591-593 Kings Road',                           'postcode': 'SW6 2EH', 'property_type': 'Office Suite', 'size': 518,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea',          'use_class': 'office',      'listing_price': 23500,   'listing_price_unit': 'pa',   'lat': 51.4809, 'lng': -0.1938, 'photo_id': 'photo-1497366216548-37526070297c', 'blurb': "Prime fitted office space in the Chelsea Design Quarter — high-quality workspace on a prestigious stretch of the King's Road."},
    {'address': 'Unit 12, The Talina Centre, Bagleys Lane',     'postcode': 'SW6 2BW', 'property_type': 'Industrial Unit','size': 1908, 'measurement_type': 'GIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Fulham',          'use_class': 'industrial',  'listing_price': 49608,   'listing_price_unit': 'pa',   'lat': 51.4779, 'lng': -0.1946, 'photo_id': 'photo-1586528116311-ad8dd3c8310d', 'blurb': 'B1 industrial warehouse and office to let with on-site parking — a versatile, well-located unit in Fulham, suitable for a range of uses.'},
    {'address': 'Britannia House, 2A Britannia Way',            'postcode': 'SW6 2HE', 'property_type': 'Office Suite', 'size': 1229, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Fulham',          'use_class': 'office',      'listing_price': 3892,    'listing_price_unit': 'pcm',  'lat': 51.4776, 'lng': -0.2001, 'photo_id': 'photo-1497366412874-3415097a27e7', 'blurb': "Boutique fitted first-floor office to let on the King's Road, Chelsea — offering high-quality workspace and excellent presentation throughout."},
    {'address': 'Worlds End Studios, 132-134 Lots Road',        'postcode': 'SW10 0RJ','property_type': 'Office Suite', 'size': 580,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea',          'use_class': 'office',      'listing_price': 1400,    'listing_price_unit': 'pcm',  'lat': 51.4800, 'lng': -0.1854, 'photo_id': 'photo-1497366754035-f200968a6e72', 'price_display': 'From £1,400 per month', 'blurb': "Modern serviced office suites to rent in Chelsea on sought-after Lots Road, moments from the King's Road and the River Thames. Various sizes available."},
    {'address': 'The Plaza Office Suite, 535 Kings Road',       'postcode': 'SW10 0SZ','property_type': 'Office Suite', 'size': 1748, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea',          'use_class': 'office',      'listing_price': 65550,   'listing_price_unit': 'pa',   'lat': 51.4869, 'lng': -0.1839, 'photo_id': 'photo-1497366811353-6870744d04b2', 'blurb': "Rarely available office and retail suite in excellent condition within The Plaza on the King's Road — includes one designated car parking space."},
    {'address': 'Bishops Park House Suite A, 25-29 Fulham High Street', 'postcode': 'SW6 3JH', 'property_type': 'Office Suite', 'size': 1075, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Fulham', 'use_class': 'office', 'listing_price': 37625, 'listing_price_unit': 'pa', 'lat': 51.4693, 'lng': -0.2173, 'photo_id': 'photo-1497366216548-37526070297c', 'blurb': 'Recently refurbished open-plan office to let in the heart of Fulham — bright, modern space in a purpose-built scheme with excellent access.'},
    {'address': 'Bishops Park House Suite B, 25-29 Fulham High Street', 'postcode': 'SW6 3JH', 'property_type': 'Office Suite', 'size': 1375, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Fulham', 'use_class': 'office', 'listing_price': 48125, 'listing_price_unit': 'pa', 'lat': 51.4694, 'lng': -0.2174, 'photo_id': 'photo-1497366412874-3415097a27e7', 'blurb': 'A larger refurbished suite within Bishops Park House — recently upgraded open-plan space to let in the heart of Fulham SW6.'},
    {'address': 'The Penthouse Office Suite, 533 Kings Road',   'postcode': 'SW10 0TZ','property_type': 'Office Suite', 'size': 2337, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': True,  'area': 'Chelsea',          'use_class': 'office',      'listing_price': 0,       'listing_price_unit': 'poa',  'lat': 51.4892, 'lng': -0.1837, 'photo_id': 'photo-1555396273-367ea4eb4db5', 'blurb': 'An exceptional penthouse office suite to let at 533 Kings Road — unrivalled position with outstanding natural light and panoramic views over Chelsea.'},
    {'address': '533 Kings Road Smart Office',                  'postcode': 'SW10 0TZ','property_type': 'Office Suite', 'size': 1000, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea',          'use_class': 'office',      'listing_price': 35000,   'listing_price_unit': 'pa',   'lat': 51.4890, 'lng': -0.1836, 'photo_id': 'photo-1497366754035-f200968a6e72', 'blurb': "Smart first floor office to let on the King's Road — well-presented space with good natural light in one of Chelsea's most prominent buildings."},
    {'address': 'Unit 10, Plato Place, 72-74 St Dionis Road',  'postcode': 'SW6 4TU', 'property_type': 'Office Suite', 'size': 1282, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Fulham',          'use_class': 'office',      'listing_price': 45000,   'listing_price_unit': 'pa',   'lat': 51.4754, 'lng': -0.2013, 'photo_id': 'photo-1497366811353-6870744d04b2', 'blurb': 'Top floor E Class office space in Fulham — bright and well-appointed with exceptional natural light and excellent transport connections.'},
    {'address': 'Fairbank Studios, Lots Road',                  'postcode': 'SW10 0RN','property_type': 'Office Suite', 'size': 480,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Chelsea',          'use_class': 'office',      'listing_price': 0,       'listing_price_unit': 'poa',  'lat': 51.4801, 'lng': -0.1852, 'photo_id': 'photo-1497366216548-37526070297c', 'blurb': 'Flexible office and retail space on a temporary basis in Chelsea — various suite sizes from 130 to 480 sq ft to suit individual requirements.'},
    # COMMERCIAL FOR SALE
    {'address': 'Units 6 & 12, The Talina Centre, Bagleys Lane','postcode': 'SW6 2BW', 'property_type': 'Industrial Unit','size': 3816, 'measurement_type': 'GIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': True,  'area': 'Fulham',          'use_class': 'industrial',  'listing_price': 1300000, 'listing_price_unit': 'sale', 'price_display': 'OIRO £1,300,000', 'lat': 51.4780, 'lng': -0.1947, 'photo_id': 'photo-1586528116311-ad8dd3c8310d', 'blurb': 'Warehouses and offices for sale at The Talina Centre — a substantial industrial and office freehold of 3,816 sq ft in Fulham SW6.'},
    {'address': 'Hurlingham Business Park Unit 6, Sulivan Road','postcode': 'SW6 3DU', 'property_type': 'Industrial Unit','size': 2867, 'measurement_type': 'GIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Fulham',          'use_class': 'industrial',  'listing_price': 1350000, 'listing_price_unit': 'sale', 'price_display': 'OIRO £1,350,000', 'lat': 51.4706, 'lng': -0.2050, 'photo_id': 'photo-1486406146926-c627a92ad1ab', 'blurb': 'Warehouse, studio and offices for sale — a self-contained freehold unit of 2,867 sq ft at Hurlingham Business Park in Fulham SW6.'},
    {'address': 'Unit 7, The Talina Centre, Bagleys Lane',      'postcode': 'SW6 2BW', 'property_type': 'Industrial Unit','size': 1270, 'measurement_type': 'GIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Fulham',          'use_class': 'industrial',  'listing_price': 450000,  'listing_price_unit': 'sale', 'price_display': 'OIRO £450,000',   'lat': 51.4778, 'lng': -0.1945, 'photo_id': 'photo-1486406146926-c627a92ad1ab', 'blurb': 'B1 industrial unit for sale with two parking spaces at The Talina Centre, Bagleys Lane — a well-positioned freehold opportunity in Fulham SW6.'},
    {'address': 'Unit 12 Freehold, The Talina Centre, Bagleys Lane', 'postcode': 'SW6 2BW', 'property_type': 'Industrial Unit', 'size': 1908, 'measurement_type': 'GIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'available', 'featured': False, 'area': 'Fulham', 'use_class': 'industrial', 'listing_price': 0, 'listing_price_unit': 'poa', 'lat': 51.4779, 'lng': -0.1946, 'photo_id': 'photo-1586528116311-ad8dd3c8310d', 'blurb': 'B1 industrial warehouse and office available freehold — with on-site parking at The Talina Centre. Also available to let.'},
    # COMMERCIAL UNDER OFFER
    {'address': 'Unit 2, Marlin House, 40 Peterborough Road',  'postcode': 'SW6 3BN', 'property_type': 'Office Suite', 'size': 236,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'under-offer', 'featured': False, 'area': 'Fulham',          'use_class': 'office',      'listing_price': 12500,   'listing_price_unit': 'pa',   'lat': 51.4779, 'lng': -0.1948, 'photo_id': 'photo-1497366412874-3415097a27e7', 'blurb': 'Fully serviced and fitted office space at Marlin House, Fulham — close to Fulham Broadway and Parsons Green station. Currently under offer.'},
    {'address': '488 Kings Road Prime Retail',                  'postcode': 'SW10 0LF','property_type': 'Retail Unit',  'size': 970,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'under-offer', 'featured': False, 'area': 'Chelsea',          'use_class': 'retail',      'listing_price': 40000,   'listing_price_unit': 'pa',   'price_display': '£38,000–£42,500 per annum', 'lat': 51.4870, 'lng': -0.1832, 'photo_id': 'photo-1604328698692-f76ea9498e76', 'blurb': "Prime retail showroom to let on the King's Road, Chelsea — a rarely available assignment on one of London's most coveted retail streets. Under offer."},
    {'address': 'Furniture & Arts Building Ground Floor, 533 Kings Road', 'postcode': 'SW10 0TZ', 'property_type': 'Office Suite', 'size': 850, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'under-offer', 'featured': False, 'area': 'Chelsea', 'use_class': 'office', 'listing_price': 30000, 'listing_price_unit': 'pa', 'lat': 51.4891, 'lng': -0.1836, 'photo_id': 'photo-1497366754035-f200968a6e72', 'blurb': 'Open plan office and showroom at 533 Kings Road — well-presented space in a landmark Chelsea building. Currently under offer.'},
    {'address': 'Hurlingham Business Park First Floor, Sulivan Road', 'postcode': 'SW6 3DU', 'property_type': 'Industrial Unit', 'size': 1620, 'measurement_type': 'GIA', 'website_listed': True, 'website_category': 'commercial', 'listing_status': 'under-offer', 'featured': False, 'area': 'Fulham', 'use_class': 'industrial', 'listing_price': 40500, 'listing_price_unit': 'pa', 'lat': 51.4707, 'lng': -0.2051, 'photo_id': 'photo-1486406146926-c627a92ad1ab', 'blurb': 'First floor office and warehouse unit with meeting rooms at Hurlingham Business Park, Fulham SW6. Currently under offer.'},
    # RESIDENTIAL
    {'address': 'Cadogan Square Apartment, Cadogan Square',     'postcode': 'SW1X',    'property_type': 'Apartment',    'size': 1850, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'residential','listing_status': 'available', 'featured': True,  'area': 'Knightsbridge',   'use_class': None,          'listing_price': 4250000, 'listing_price_unit': 'sale', 'beds': 3, 'baths': 2, 'lat': 51.4985, 'lng': -0.1607, 'photo_id': 'photo-1568605114967-8130f3a36994', 'blurb': 'A beautifully proportioned lateral apartment in a handsome red-brick mansion building, moments from the boutiques of Sloane Street and the gardens of Cadogan Square.'},
    {'address': 'Imperial Wharf Riverside Apartment, Imperial Wharf', 'postcode': 'SW6', 'property_type': 'Apartment', 'size': 1100, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'residential', 'listing_status': 'available', 'featured': False, 'area': 'Fulham', 'use_class': None, 'listing_price': 5400, 'listing_price_unit': 'pcm', 'beds': 2, 'baths': 2, 'lat': 51.4734, 'lng': -0.1818, 'photo_id': 'photo-1502672260266-1c1ef2d93688', 'blurb': 'A bright contemporary apartment with a private balcony overlooking the river, available furnished within a sought-after riverside development with concierge.'},
    {'address': 'Parsons Green Garden Flat, Parsons Green',     'postcode': 'SW6',     'property_type': 'Garden Flat',  'size': 900,  'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'residential','listing_status': 'available', 'featured': False, 'area': 'Fulham',          'use_class': None,          'listing_price': 3950,    'listing_price_unit': 'pcm',  'beds': 2, 'baths': 1, 'lat': 51.4753, 'lng': -0.2012, 'photo_id': 'photo-1493809842364-78817add7ffb', 'blurb': "A delightful raised ground and lower floor flat with its own private garden, set just a short stroll from the Green and the shops of the New King's Road."},
    {'address': "Queen's Gate Mews House, Queen's Gate Mews",   'postcode': 'SW7',     'property_type': 'Mews House',   'size': 1600, 'measurement_type': 'NIA', 'website_listed': True, 'website_category': 'residential','listing_status': 'available', 'featured': False, 'area': 'South Kensington','use_class': None,          'listing_price': 2850000, 'listing_price_unit': 'sale',  'beds': 3, 'baths': 2, 'lat': 51.4944, 'lng': -0.1768, 'photo_id': 'photo-1570129477492-45c003edd2be', 'blurb': 'A charming and immaculately presented mews house on a quiet cobbled lane, offering rare off-street parking and a flood of natural light throughout.'},
]

def run_import():
    added = 0
    skipped = 0
    for l in listings:
        existing = Property.query.filter_by(address=l['address'], postcode=l['postcode']).first()
        if existing:
            skipped += 1
            continue
        p = Property(**l)
        db.session.add(p)
        added += 1
    db.session.commit()
    total = Property.query.count()
    print(f'Done. Added {added}, skipped {skipped} (already exist). Total in DB: {total}')
    return added

if __name__ == '__main__':
    with app.app_context():
        run_import()
else:
    # Called as module from serve.py — app context already active
    run_import()
