f = r'C:\Users\SamuelC\property-db\templates\dashboard.html'
with open(f, 'r', encoding='utf-8', errors='replace') as fh:
    lines = fh.readlines()

new_block = [
    '    <div class="panel-body" id="enquiry-list">\n',
    '      {% if open_enquiries %}\n',
    '        {% for e in open_enquiries %}\n',
    '        {% set tl = e.traffic_light %}\n',
    "        <div class=\"enquiry-item\" style=\"border-left:3px solid {{ '#c62828' if tl == 'red' else '#e65100' if tl == 'amber' else '#1b7a3f' if tl == 'green' else '#9aa0a6' }}\">\n",
    '          <div style="display:flex;align-items:flex-start;gap:8px">\n',
    '            <span style="font-size:14px;flex-shrink:0;margin-top:1px">{{ e.traffic_emoji }}</span>\n',
    '            <div style="flex:1;min-width:0">\n',
    "              <a href=\"{{ url_for('enquiry_edit', id=e.id) }}\" style=\"font-size:12.5px;font-weight:600;color:#c8601a;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis\">{{ e.subject }}</a>\n",
    '              <div style="font-size:11px;color:#5f6368;margin-top:2px">\n',
    '                {% if e.enquiry_type %}<strong>{{ e.enquiry_type }}</strong>{% endif %}\n',
    '                {% if e.fee_earner %} &middot; {{ e.fee_earner }}{% endif %}\n',
    '              </div>\n',
    '              {% if e.contact %}\n',
    '              <div style="font-size:11px;color:#5f6368;margin-top:2px">\n',
    '                {{ e.contact.full_name }}{% if e.contact.phone %} &mdash; {{ e.contact.phone }}{% endif %}\n',
    '              </div>\n',
    '              {% endif %}\n',
    '              {% if e.linked_property %}\n',
    '              <div style="font-size:11px;color:#9aa0a6;margin-top:1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">\n',
    '                {{ e.linked_property.address }}\n',
    '              </div>\n',
    '              {% endif %}\n',
    '              <div style="font-size:10.5px;margin-top:4px;display:flex;gap:8px;flex-wrap:wrap">\n',
    '                {% if e.last_contact_date %}\n',
    "                <span style=\"color:#5f6368\">Last: {{ e.last_contact_date.strftime('%d %b') }}</span>\n",
    '                {% endif %}\n',
    '                {% if e.next_follow_up %}\n',
    "                <span style=\"color:{{ '#c62828' if e.next_follow_up <= today else '#1b7a3f' }};font-weight:600\">\n",
    "                  Follow-up: {{ e.next_follow_up.strftime('%d %b %Y') }}\n",
    '                </span>\n',
    '                {% endif %}\n',
    '              </div>\n',
    '            </div>\n',
    '          </div>\n',
    "          <form method=\"post\" action=\"{{ url_for('enquiry_log_contact', id=e.id) }}\"\n",
    '                style="display:flex;gap:4px;margin-top:6px;align-items:center">\n',
    '            <input type="date" name="next_follow_up"\n',
    '                   style="flex:1;font-size:11px;padding:3px 6px;border:1px solid #dde0e4;border-radius:4px"\n',
    '                   title="Set next follow-up date">\n',
    '            <button type="submit" class="btn btn-xs"\n',
    '                    style="background:#1b7a3f;color:#fff;border:none;font-size:10.5px;white-space:nowrap">\n',
    '              Log Contact\n',
    '            </button>\n',
    '          </form>\n',
    '        </div>\n',
    '        {% endfor %}\n',
    '      {% else %}\n',
    '        <div class="panel-empty">\n',
    '          No open enquiries.<br>\n',
    "          <a href=\"{{ url_for('enquiry_new') }}\" style=\"color:var(--orange)\">Record an enquiry</a>\n",
    '        </div>\n',
    '      {% endif %}\n',
    '    </div>\n',
    '  </div>\n',
]

new_lines = lines[:185] + new_block + lines[220:]
with open(f, 'w', encoding='utf-8') as fh:
    fh.writelines(new_lines)
print(f'Done. {len(new_lines)} lines written.')
